apiVersion: v1
clusters:
- cluster:
    server: https://rancher.trv.cloud/k8s/clusters/c-m-2pn22fht
  name: search-backend-stage-eu-dus1
- cluster:
    server: https://rancher.trv.cloud/k8s/clusters/c-m-5hg2x9b6
  name: tools-prod-eu-dus1
- cluster:
    server: https://rancher.trv.cloud/k8s/clusters/c-m-pwhdkzcs
  name: tools-stage-eu-dus1
contexts:
- context:
    cluster: search-backend-stage-eu-dus1
    user: search-backend-stage-eu-dus1
  name: rancher-search-backend-stage-eu-dus1
- context:
    cluster: tools-prod-eu-dus1
    user: tools-prod-eu-dus1
  name: rancher-tools-prod-eu-dus1
- context:
    cluster: tools-stage-eu-dus1
    user: tools-stage-eu-dus1
  name: rancher-tools-stage-eu-dus1
current-context: ""
kind: Config
preferences: {}
users:
- name: search-backend-stage-eu-dus1
  user:
    token: kubeconfig-u-wgqom6dhf59br95:rbq4mvlgw85mxvl927jjh688l8ztsq4v2h99ds9jhp6wpkdzppk9wq
- name: tools-prod-eu-dus1
  user:
    token: kubeconfig-u-wgqom6dhf5t89v2:wk9j6qc6k82k6vzr9p5fmlsbctmjv6rh8mbdqrb6wpvgqfkpfbpzvn
- name: tools-stage-eu-dus1
  user:
    token: kubeconfig-u-wgqom6dhf5jnks8:lpxqq5rxpxfq85b25chsfx8wdq4zqxvnkmgvxv4p262qxlbjtg7qld
